Fix #30
omnixerio/devices-mod pull request #33
Opened 2022-10-25 23:08 UTC by JosephYapYEEEEEEEEEEEEEEEEEEEEEEEEEEEET

2022-10-25 23:08 UTC, JosephYapYEEEEEEEEEEEEEEEEEEEEEEEEEEEET commented
🤦 fixes #30 not MrCrayfish#30

2022-10-25 23:13 UTC, Qboi123 submitted a review, later dismissed

2022-10-25 23:13 UTC, Qboi123 commented on common/src/main/java/com/ultreon/devices/core/Laptop.java
> +        drawString(pose, getFont(), "Beta " + Reference.VERSION, posX + BORDER + 5, posY + BORDER + 5, Color.WHITE.getRGB()); // TODO: figure out a better way to do this
Rather allow `isDevelopmentPreview` to be used. As it would be used in exclusive previews that sometimes gets shared.

2022-10-25 23:27 UTC, Jab125 commented on common/src/main/java/com/ultreon/devices/core/Laptop.java
> +        drawString(pose, getFont(), "Beta " + Reference.VERSION, posX + BORDER + 5, posY + BORDER + 5, Color.WHITE.getRGB()); // TODO: figure out a better way to do this
There's a TODO there, also was edited in a rush on https://vscode.dev

2022-10-25 23:46 UTC, Qboi123 commented on common/src/main/java/com/ultreon/devices/core/Laptop.java
> +        drawString(pose, getFont(), "Beta " + Reference.VERSION, posX + BORDER + 5, posY + BORDER + 5, Color.WHITE.getRGB()); // TODO: figure out a better way to do this
> There's a TODO there, also was edited in a rush on https://vscode.dev

Where? @Jab125

2022-10-26 08:40 UTC, Jab125 requested changes

2022-10-26 08:40 UTC, Jab125 commented on common/src/main/java/com/ultreon/devices/core/Laptop.java
> +        drawString(pose, getFont(), "Beta " + Reference.VERSION, posX + BORDER + 5, posY + BORDER + 5, Color.WHITE.getRGB()); // TODO: figure out a better way to do this
```suggestion
        if (!Devices.DEVELOPER_MODE) { // TODO: figure out a way to separate the build number
             if (Devices.isDevelopmentPreview()) {
                 drawString(pose, getFont(), "Development Preview - " + Reference.VERSION, posX + BORDER + 5, posY + BORDER + 5, Color.WHITE.getRGB());
             } else {
                 drawString(pose, getFont(), "Beta " + Reference.VERSION, posX + BORDER + 5, posY + BORDER + 5, Color.WHITE.getRGB());
             }
         } else {
             drawString(pose, getFont(), "Developer Version - " + Reference.VERSION, posX + BORDER + 5, posY + BORDER + 5, Color.WHITE.getRGB());
         }
```

2022-10-26 08:41 UTC, Jab125 approved these changes

2022-10-26 09:04 UTC, merged