Update fabric json
omnixerio/devices-mod pull request #40
Opened 2022-11-04 04:40 UTC by Qboi123

Add some socials using ModMenu, updater using ModUpdater and add some more contact info.

2022-11-04 04:56 UTC, Jab125 requested changes

2022-11-04 04:56 UTC, Jab125 commented on fabric/src/main/resources/fabric.mod.json
> +      "strategy": "curseforge",
curseforge doesn't work

2022-11-04 04:56 UTC, Jab125 commented on fabric/src/main/resources/fabric.mod.json
> +        "modmenu.youtube": "https://youtube.com/@ultreon",
this can be replaced with a "Person" object in the "authors" object

2022-11-04 04:56 UTC, Jab125 commented on fabric/src/main/resources/fabric.mod.json
> -    "MinecraftDoodler",
MinecraftDoodler contributed to GitWeb

2022-11-04 14:18 UTC, QboiDev commented on fabric/src/main/resources/fabric.mod.json
> -    "MinecraftDoodler",
Yeah, I know, but he was in there 2 times,

2022-11-04 14:19 UTC, QboiDev commented on fabric/src/main/resources/fabric.mod.json
> +      "strategy": "curseforge",
Uhm, maybe you can try fix it? I've seen this in ModMenu's `fabric.mod.json`.
I basically changed the ID.

2022-11-04 14:20 UTC, Qboi123 commented on fabric/src/main/resources/fabric.mod.json
> +        "modmenu.youtube": "https://youtube.com/@ultreon",
Uhm, how? I actually wanted to add YouTube to the links in ModMenu.

2022-12-08 21:22 UTC, Qboi123 commented on fabric/src/main/resources/fabric.mod.json
> -    "MinecraftDoodler",
@Jab125 check the 2nd one in the list.

2023-06-22 17:49 UTC, Qboi123 commented on fabric/src/main/resources/fabric.mod.json
> +      "strategy": "curseforge",
Ok, removed it.

2023-06-22 18:04 UTC, merged