Move DV Tests to UltreonLib Tests
omnixerio/devices-mod pull request #83
Opened 2023-10-16 22:16 UTC by XyperCode

Using the UltreonLib Test Screen API we can remove the need of the DV TEST buttons in the title screen.

## Extra Dependencies:
 * [UltreonLib](https://github.com/Ultreon/ultreonlib)

2023-10-24 04:08 UTC, Jab125 requested changes
Also, make sure the mod doesn't need to have UltreonLib in production

2023-10-24 04:08 UTC, Jab125 commented on common/src/main/java/com/ultreon/devices/core/client/debug/ClientAppDebug.java
>  public class ClientAppDebug {
just remove the entire class, this isn't an api

2023-10-24 09:01 UTC, XyperCode commented on common/src/main/java/com/ultreon/devices/core/client/debug/ClientAppDebug.java
>  public class ClientAppDebug {
Okidoki, will do that.

2023-10-24 09:02 UTC, XyperCode commented
> Also, make sure the mod doesn't need to have UltreonLib in production

I doesn't need it *yet*.
But 2.0 will require it probably.

2025-10-07 23:44 UTC, QboiDev commented
UltreonLib support has ended, not needed anymore.

2025-10-07 23:44 UTC, closed without merging